import Head from "next/head";
import type { NextPage } from "next";
import tw from "twin.macro";
import GlobalStyles from "../styles/global-styles";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>My Template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <GlobalStyles />
      <main>
        <p css={tw`text-3xl`}>Hello!</p>
      </main>
    </>
  );
};

export default Home;
