name: Setup

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  CI:
    name: set up
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable
